# Generated by Django 2.0 on 2018-01-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentpost',
            options={'ordering': ['-CommentTime'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
