# Generated by Django 2.0 on 2018-03-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Icon',
            field=models.ImageField(default='user_icon/default.jpg', upload_to='user_icon', verbose_name='头像'),
        ),
    ]
