# Generated by Django 2.0 on 2018-03-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Icon',
            new_name='icon',
        ),
    ]
