# Generated by Django 2.0 on 2018-03-21 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_auto_20180318_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=200, verbose_name='留言信息')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.User', verbose_name='留言用户')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['-time'],
            },
        ),
    ]
