# Generated by Django 2.0 on 2018-01-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=50, verbose_name='歌名')),
                ('music_word', models.CharField(max_length=100, verbose_name='歌词')),
                ('music_url', models.URLField(verbose_name='歌词地址')),
                ('singer', models.CharField(max_length=50, verbose_name='歌手')),
            ],
            options={
                'verbose_name': '博客类型',
                'verbose_name_plural': '博客类型',
            },
        ),
    ]
